### ISSUE TITLE
Docker + WebRTC Port ranges

### ISSUE THREAD

**Issue by andrewmunro** [geckosio/geckos.io#40]
Not really an issue, more of a query...

I'm trying to configure geckos to run in a docker image for local dev and testing. 
I've been debugging why geckos can't seem to connect to the server and narrowed it down to not forwarding a wide range of ports that gets returned from the "additional-candidates" request (http://localhost:9208/.wrtc/v1/connections/HoFlaeDUQ6IsUan1CO4dTIbz/additional-candidates).

![image](https://user-images.githubusercontent.com/1107388/88343935-743a5a80-cd3a-11ea-87cd-44e3e4536f26.png)

As far as I can tell, these ports seem to vary quite wildly. Is there any way to configure the range, or maybe get a list of which ports I need to port forward? I've tried something like 5000-65000 but then I just hit a file limit :/

Here's my current docker-compose configuration:

```
version: '3'
services:
    client:
        image: nginx
        volumes:
            - ./bin/www:/usr/share/nginx/html
        ports:
            - '${PORT:-8080}:80'
    server:
        image: node:13
        command: bash -c "yarn --production && node server.js"
        volumes:
            - ./bin:/app
            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - yarn-cache:/root/.yarn-cache
        working_dir: /app
        ports:
            - '9208:9208/tcp'
            - '9208:9208/udp'

volumes:
    yarn-cache:

```

**Comment by andrewmunro** [comment]
Ok I realise you have actually documented this under https://github.com/geckosio/geckos.io#deployment.
Maybe what I'm asking for (limiting port range) is not possible.

For now, I've figured out a workaround by running that container on the host network. For anyone with a similar issue, this works for me

Note: docker-compose v3.4
```
version: '3.4'
services:
    client:
        image: nginx
        volumes:
            - ./bin/www:/usr/share/nginx/html
        ports:
            - '${PORT:-80}:80'
    server:
        image: node:13
        *network_mode: host*
        command: bash -c "yarn --production && node server.js"
        volumes:
            - ./bin:/app
            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - yarn-cache:/root/.yarn-cache
        working_dir: /app

volumes:
    yarn-cache:
```
